[ids]

*

[main]

leftshift+leftmeta+f23 = leftmeta
capslock = overload(control, esc)
enter = overload(control, enter)
space = overloadt(nav, space, 150)
' = rightshift
rightshift = '

[ = backspace
backspace = [

d+s = layer(leftchord)

[nav]
h = left
j = down
k = up
l = right
u = home
o = end
i = pageup
p = pagedown
# kde workspace switching
a = macro(leftmeta+1)
s = macro(leftmeta+2)
d = macro(leftmeta+3)
f = macro(leftmeta+4)
# firefox tab switching
q = macro(A-1)
w = macro(A-2)
e = macro(A-3)
r = macro(A-4)
t = macro(A-5)
1 = macro(A-6)
2 = macro(A-7)
3 = macro(A-8)
4 = macro(A-9)
n = macro(C-S-tab)
m = macro(C-tab)

# [symbols]
# lets alt+numbers still work for firefox
# 1 = macro(A-1)
# 2 = macro(A-2)
# 3 = macro(A-3)
# 4 = macro(A-4)
# 5 = macro(A-5)
# 6 = macro(A-6)
# 7 = macro(A-7)
# 8 = macro(A-8)
# 9 = macro(A-9)
# 0 = macro(A-0)

# q = !
# w = @
# e = macro(S-3)
# r = $
# t = %
# y = ^
# u = &
# i = (
# o = )
# p = *
# h = -
# j = =
# k = [
# l = ]
# n = _
# m = +
# , = leftbrace
# . = rightbrace
# 7 = \
# 8 = |
# ' = '
# slash = "


# [intellij]
# # debugging, matches layout in GUI window
# tab = f9
# q = f8
# w = f7
# e = macro(S-f8)

# # general chords
# r = macro(S-f10)
# d = macro(S-f9)
# t = macro(A-f12)
# a = macro(C-S-f12)
# v = macro(C-S-`)

# # callum chords
# s = oneshot(meta)
# d = oneshot(alt)
# f = oneshot(control)

# j = oneshot(control)
# k = oneshot(alt)
# l = oneshot(meta)
