[ids]

*

[main]

leftshift+leftmeta+f23 = leftmeta
# leftshift+leftmeta+f23 = layer(leftmodifiers)
capslock = overload(control, esc)
tab = overload(vimmer, tab)
leftalt = layer(vimmer)
enter = overload(leftmodifiers, enter)
space = overloadt(nav, space, 150)
' = rightshift
rightshift = '

[ = backspace
backspace = [

[vimmer]
h = left
j = down
k = up
l = right
u = home
o = end
i = pageup
p = pagedown

[nav]
# kde workspace switching
a = macro(leftmeta+1)
s = macro(leftmeta+2)
d = macro(leftmeta+3)
f = macro(leftmeta+4)

# firefox tab switching
q = macro(A-1)
w = macro(A-2)
e = macro(A-3)
r = macro(A-4)
t = macro(A-5)
1 = macro(A-6)
2 = macro(A-7)
3 = macro(A-8)
4 = macro(A-9)

j = oneshot(control)
k = oneshot(alt)
l = oneshot(meta)
; = oneshot(shift)

n = macro(C-pageup)
m = macro(C-pagedown)

# these are originally shadowed by the backspace/shift moves in main, restore them in this layer
' = '
" = "
[ = [
capslock = capslock

[leftmodifiers]

# yakuake
t = f12

# firefox tab search
r = macro(C-S-f)

a = oneshot(shift)
s = oneshot(meta)
f = oneshot(control)

# NOTICE: alt isn't used as frequently as ctrl so we substitute it
# to make activating the vimmer layer easier
d = layer(vimmer)

g = oneshot(alt)
