[ids]

*

[global]
chord_timeout = 40

[main]

leftshift+leftmeta+f23 = leftmeta
# left = overload(control, esc)
capslock = overload(control, esc)
enter = overload(control, enter)
space = overloadt(nav, space, 250)

f+d = leftshift
s+d = leftcontrol
a+s = leftmeta
a+f = leftalt
j+k = rightshift
k+l = rightcontrol
l+; = rightmeta
# j+; = rightalt
# rightalt is weird on linux
j+; = leftalt
[ = backspace

leftalt = overloadt(symbols, leftalt, 250)

[nav]
h = left
j = down
k = up
l = right
u = home
o = end
i = pageup
p = pagedown

[symbols]
q = !
w = @
e = macro(S-3)
r = $
t = %
y = ^
u = &
i = *
o = (
p = )
h = -
j = =
k = [
l = ]
; = \
n = _
m = +
, = {
. = }
/ = |
