theme = "gruvbox_dark_hard"

[editor.file-picker]
hidden = false

[editor]
bufferline = "multiple"
cursorline = true

[keys.normal.space]
space = "file_picker"

[keys.normal.space.q]
q = ":qa"

[keys.normal.space.f]
s = ":wa"
